import type { Metadata } from 'next'
import React from 'react'
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="min-h-screen bg-gradient-radial from-blue-200 via-blue-100 to-white text-gray-800">
      {children}
    </div>
  )
}
